### ISSUE TITLE
1

### ISSUE THREAD

**Issue by 0moyi0-2024** [singularity-s0/fudan_sports_autoreserve#11]
可以交流一下你为什么对于学校体育馆的那些功能链接那么熟悉吗？存粹交个朋友，我是20级的硕士生

**Comment by singularity-s0** [comment]
可以通过逆向工程的方法（例如抓包）了解系统内部的实现。

**Comment by 0moyi0-2024** [comment]
交个朋友学习技术可吗？vx15779872616




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月3日(星期天) 晚上9:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [singularity-s0/fudan_sports_autoreserve] 1 (Issue #11)





 
可以通过逆向工程的方法（例如抓包）了解系统内部的实现。
