### ISSUE TITLE
时间精确输入

### ISSUE THREAD

**Issue by durianmangosteen** [singularity-s0/fudan_sports_autoreserve#5]
我尝试了各种输入，但是依然是
INFO                                Skipping Available Option: 2023-05-26 08:00
INFO				Skipping Available Option: 2023-05-26 09:00
INFO				Skipping Available Option: 2023-05-26 10:00
INFO				Skipping Available Option: 2023-05-26 11:00
INFO				Skipping Available Option: 2023-05-26 12:00
请问作者有时间的精确匹配有范例吗？应该怎么来输入呢？（python学艺不精，还望作者体谅）

**Comment by singularity-s0** [comment]
你可以直接复制粘贴Skipping Available Options后面的内容。

**Comment by durianmangosteen** [comment]
我把时间复制粘贴了，格式如下
DATE = "2023-05-26"
TIME = "2023-05-26 13:00"
但是最后依然无法预约
Skipping Available Option: 2023-05-26 13:00
怎么来解决呢

**Comment by singularity-s0** [comment]
应该是

DATE = "2023-05-26"
TIME = "13:00"

**Comment by singularity-s0** [comment]
理论上来说这样肯定是没有问题的。相关代码在 apis.py 144行和184行，如果依然不行的话可以检查一下为什么144行的if判断没有通过
