### ISSUE TITLE
自动运行

### ISSUE THREAD

**Issue by durianmangosteen** [singularity-s0/fudan_sports_autoreserve#9]
请问如何能设置这个程序在早上7:00定时运行呢？还有如何实现多个时间段的预约呢？

**Comment by singularity-s0** [comment]
> 请问如何能设置这个程序在早上7:00定时运行呢？

本仓库不提供与项目无关的技术支持，但是作为参考，你可以考虑设置`cron`任务（Windows平台可采用Task Scheduler）。注意，你需要确保执行此脚本的设备在早上7:00处于开机状态。

> 如何实现多个时间段的预约呢？

设置多个`cron`任务
